# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LostCitiesHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LostCitiesHelper
	pod 'Then'
	pod 'SnapKit', '~> 4.0.0'

end
